import { Section, CatalogItem, CompanySettings } from './types';

export const FOUNDATIONS = [
  { name: 'Ленточный', pricePerSqm: 4500 },
  { name: 'Плитный', pricePerSqm: 6000 },
  { name: 'Свайный', pricePerSqm: 3500 },
];

export const READINESS_OPTIONS = [
  { value: 'box', label: 'Коробка дома' },
  { value: 'warm', label: 'Тёплый контур' },
  { value: 'turnkey', label: 'Под ключ' },
];

export const PACKAGES = [
  {
    id: 'economy',
    name: 'Эконом',
    description: 'Базовые отделки, стандартные материалы',
    pricePerSqm: 25000,
  },
  {
    id: 'standard',
    name: 'Стандарт',
    description: 'Оптимальный набор материалов и работ',
    pricePerSqm: 35000,
    recommended: true,
  },
  {
    id: 'comfort',
    name: 'Комфорт',
    description: 'Премиальные материалы и дизайнерские решения',
    pricePerSqm: 50000,
  },
];

export const SECTIONS: Section[] = [
  { id: 'foundation', name: 'Фундамент', sort_order: 1 },
  { id: 'walls', name: 'Коробка дома', sort_order: 2 },
  { id: 'roof', name: 'Кровля', sort_order: 3 },
  { id: 'engineering', name: 'Инженерные сети', sort_order: 4 },
  { id: 'facade', name: 'Наружная отделка', sort_order: 5 },
  { id: 'interior', name: 'Внутренняя отделка', sort_order: 6 },
  { id: 'landscaping', name: 'Благоустройство', sort_order: 7 },
];

export const CATALOG_ITEMS: CatalogItem[] = [
  {
    id: 'f1',
    section_id: 'foundation',
    name: 'Земляные работы',
    unit: 'м²',
    base_qty_formula: 'area',
    variants: [
      { name: 'Стандарт', material_price: 200, work_price: 300, delivery_price: 50 },
    ],
    is_required: true,
    economy_default: 'Стандарт',
    standard_default: 'Стандарт',
    comfort_default: 'Стандарт',
    sort_order: 1,
  },
  {
    id: 'f2',
    section_id: 'foundation',
    name: 'Ленточный фундамент',
    unit: 'м²',
    base_qty_formula: 'area',
    variants: [
      { name: 'Ленточный', material_price: 2500, work_price: 1800, delivery_price: 200 },
      { name: 'Плитный', material_price: 3500, work_price: 2300, delivery_price: 200 },
      { name: 'Свайный', material_price: 1800, work_price: 1600, delivery_price: 100 },
    ],
    is_required: true,
    economy_default: 'Ленточный',
    standard_default: 'Ленточный',
    comfort_default: 'Плитный',
    sort_order: 2,
  },
  {
    id: 'w1',
    section_id: 'walls',
    name: 'Газоблок 300мм',
    unit: 'м²',
    base_qty_formula: 'area * 1.3',
    variants: [
      { name: 'Газоблок 300мм', material_price: 1800, work_price: 1200, delivery_price: 200 },
      { name: 'Газоблок 400мм', material_price: 2300, work_price: 1400, delivery_price: 200 },
      { name: 'Кирпич', material_price: 3000, work_price: 2200, delivery_price: 300 },
    ],
    is_required: true,
    economy_default: 'Газоблок 300мм',
    standard_default: 'Газоблок 300мм',
    comfort_default: 'Газоблок 400мм',
    sort_order: 1,
  },
  {
    id: 'w2',
    section_id: 'walls',
    name: 'Перекрытия',
    unit: 'м²',
    base_qty_formula: 'area',
    variants: [
      { name: 'Деревянные балки', material_price: 1500, work_price: 1000, delivery_price: 150 },
      { name: 'Бетонные плиты', material_price: 2800, work_price: 800, delivery_price: 200 },
      { name: 'Монолитное ЖБ', material_price: 3200, work_price: 1200, delivery_price: 250 },
    ],
    is_required: true,
    economy_default: 'Деревянные балки',
    standard_default: 'Бетонные плиты',
    comfort_default: 'Монолитное ЖБ',
    sort_order: 2,
  },
  {
    id: 'r1',
    section_id: 'roof',
    name: 'Кровля',
    unit: 'м²',
    base_qty_formula: 'area * 1.2',
    variants: [
      { name: 'Металлочерепица', material_price: 1000, work_price: 600, delivery_price: 200 },
      { name: 'Мягкая кровля', material_price: 1300, work_price: 700, delivery_price: 200 },
      { name: 'Натуральная черепица', material_price: 2500, work_price: 900, delivery_price: 300 },
    ],
    is_required: true,
    economy_default: 'Металлочерепица',
    standard_default: 'Мягкая кровля',
    comfort_default: 'Натуральная черепица',
    sort_order: 1,
  },
  {
    id: 'r2',
    section_id: 'roof',
    name: 'Стропильная система',
    unit: 'м²',
    base_qty_formula: 'area * 1.2',
    variants: [
      { name: 'Стандарт', material_price: 800, work_price: 600, delivery_price: 100 },
    ],
    is_required: true,
    economy_default: 'Стандарт',
    standard_default: 'Стандарт',
    comfort_default: 'Стандарт',
    sort_order: 2,
  },
  {
    id: 'e1',
    section_id: 'engineering',
    name: 'Электропроводка',
    unit: 'м²',
    base_qty_formula: 'area',
    variants: [
      { name: 'Базовая', material_price: 800, work_price: 1200, delivery_price: 100 },
      { name: 'Расширенная', material_price: 1200, work_price: 1500, delivery_price: 150 },
    ],
    is_required: true,
    economy_default: 'Базовая',
    standard_default: 'Расширенная',
    comfort_default: 'Расширенная',
    sort_order: 1,
  },
  {
    id: 'e2',
    section_id: 'engineering',
    name: 'Отопление',
    unit: 'м²',
    base_qty_formula: 'area',
    variants: [
      { name: 'Газовое', material_price: 1500, work_price: 1000, delivery_price: 200 },
      { name: 'Электрическое', material_price: 2000, work_price: 1200, delivery_price: 200 },
    ],
    is_required: true,
    economy_default: 'Газовое',
    standard_default: 'Газовое',
    comfort_default: 'Электрическое',
    sort_order: 2,
  },
  {
    id: 'e3',
    section_id: 'engineering',
    name: 'Водоснабжение и канализация',
    unit: 'м²',
    base_qty_formula: 'area',
    variants: [
      { name: 'Стандарт', material_price: 600, work_price: 800, delivery_price: 100 },
    ],
    is_required: true,
    economy_default: 'Стандарт',
    standard_default: 'Стандарт',
    comfort_default: 'Стандарт',
    sort_order: 3,
  },
  {
    id: 'e4',
    section_id: 'engineering',
    name: 'Вентиляция',
    unit: 'м²',
    base_qty_formula: 'area',
    variants: [
      { name: 'Естественная', material_price: 200, work_price: 300, delivery_price: 50 },
      { name: 'Принудительная', material_price: 500, work_price: 600, delivery_price: 100 },
    ],
    is_required: false,
    economy_default: 'Естественная',
    standard_default: 'Принудительная',
    comfort_default: 'Принудительная',
    sort_order: 4,
  },
  {
    id: 'fa1',
    section_id: 'facade',
    name: 'Фасадная отделка',
    unit: 'м²',
    base_qty_formula: 'area * 1.3',
    variants: [
      { name: 'Штукатурка', material_price: 600, work_price: 800, delivery_price: 100 },
      { name: 'Клинкерная плитка', material_price: 1500, work_price: 1200, delivery_price: 200 },
      { name: 'Вентилируемый фасад', material_price: 1800, work_price: 1500, delivery_price: 250 },
    ],
    is_required: true,
    economy_default: 'Штукатурка',
    standard_default: 'Штукатурка',
    comfort_default: 'Вентилируемый фасад',
    sort_order: 1,
  },
  {
    id: 'fa2',
    section_id: 'facade',
    name: 'Окна',
    unit: 'м²',
    base_qty_formula: 'area * 0.25',
    variants: [
      { name: 'ПВХ двухкамерные', material_price: 2000, work_price: 500, delivery_price: 200 },
      { name: 'ПВХ трёхкамерные', material_price: 2500, work_price: 600, delivery_price: 200 },
      { name: 'Дерево-алюминий', material_price: 4000, work_price: 800, delivery_price: 300 },
    ],
    is_required: true,
    economy_default: 'ПВХ двухкамерные',
    standard_default: 'ПВХ трёхкамерные',
    comfort_default: 'Дерево-алюминий',
    sort_order: 2,
  },
  {
    id: 'fa3',
    section_id: 'facade',
    name: 'Входная дверь',
    unit: 'шт',
    base_qty_formula: '1',
    variants: [
      { name: 'Стальная эконом', material_price: 5000, work_price: 1000, delivery_price: 500 },
      { name: 'Стальная утеплённая', material_price: 8000, work_price: 1200, delivery_price: 500 },
      { name: 'Премиум', material_price: 15000, work_price: 1500, delivery_price: 1000 },
    ],
    is_required: true,
    economy_default: 'Стальная эконом',
    standard_default: 'Стальная утеплённая',
    comfort_default: 'Премиум',
    sort_order: 3,
  },
  {
    id: 'fa4',
    section_id: 'facade',
    name: 'Утепление фасада',
    unit: 'м²',
    base_qty_formula: 'area * 1.3',
    variants: [
      { name: 'Минвата 100мм', material_price: 400, work_price: 600, delivery_price: 100 },
      { name: 'Минвата 150мм', material_price: 600, work_price: 800, delivery_price: 150 },
      { name: 'ПИР-плита', material_price: 1000, work_price: 700, delivery_price: 150 },
    ],
    is_required: true,
    economy_default: 'Минвата 100мм',
    standard_default: 'Минвата 150мм',
    comfort_default: 'ПИР-плита',
    sort_order: 4,
  },
  {
    id: 'in1',
    section_id: 'interior',
    name: 'Отделка стен',
    unit: 'м²',
    base_qty_formula: 'area * 2',
    variants: [
      { name: 'Шпатлёвка и покраска', material_price: 300, work_price: 400, delivery_price: 50 },
      { name: 'Обои', material_price: 600, work_price: 300, delivery_price: 50 },
      { name: 'Декоративная штукатурка', material_price: 1200, work_price: 600, delivery_price: 100 },
    ],
    is_required: false,
    economy_default: 'Шпатлёвка и покраска',
    standard_default: 'Обои',
    comfort_default: 'Декоративная штукатурка',
    sort_order: 1,
  },
  {
    id: 'in2',
    section_id: 'interior',
    name: 'Полы',
    unit: 'м²',
    base_qty_formula: 'area',
    variants: [
      { name: 'Линолеум', material_price: 500, work_price: 300, delivery_price: 100 },
      { name: 'Ламинат', material_price: 1200, work_price: 400, delivery_price: 150 },
      { name: 'Паркет', material_price: 2500, work_price: 600, delivery_price: 200 },
    ],
    is_required: false,
    economy_default: 'Линолеум',
    standard_default: 'Ламинат',
    comfort_default: 'Паркет',
    sort_order: 2,
  },
  {
    id: 'in3',
    section_id: 'interior',
    name: 'Двери межкомнатные',
    unit: 'шт',
    base_qty_formula: 'floors * 4',
    variants: [
      { name: 'ДВП эконом', material_price: 2000, work_price: 300, delivery_price: 200 },
      { name: 'МДФ стандарт', material_price: 4000, work_price: 400, delivery_price: 300 },
      { name: 'Массив дуба', material_price: 8000, work_price: 600, delivery_price: 400 },
    ],
    is_required: false,
    economy_default: 'ДВП эконом',
    standard_default: 'МДФ стандарт',
    comfort_default: 'Массив дуба',
    sort_order: 3,
  },
  {
    id: 'in4',
    section_id: 'interior',
    name: 'Потолки',
    unit: 'м²',
    base_qty_formula: 'area',
    variants: [
      { name: 'Побелка', material_price: 100, work_price: 200, delivery_price: 20 },
      { name: 'Подвесной гипсокартон', material_price: 500, work_price: 400, delivery_price: 100 },
      { name: 'Натяжной потолок', material_price: 1200, work_price: 600, delivery_price: 200 },
    ],
    is_required: false,
    economy_default: 'Побелка',
    standard_default: 'Подвесной гипсокартон',
    comfort_default: 'Натяжной потолок',
    sort_order: 4,
  },
  {
    id: 'in5',
    section_id: 'interior',
    name: 'Сантехника',
    unit: 'шт',
    base_qty_formula: 'floors * 2',
    variants: [
      { name: 'Эконом', material_price: 10000, work_price: 5000, delivery_price: 2000 },
      { name: 'Стандарт', material_price: 20000, work_price: 8000, delivery_price: 3000 },
      { name: 'Премиум', material_price: 40000, work_price: 12000, delivery_price: 5000 },
    ],
    is_required: false,
    economy_default: 'Эконом',
    standard_default: 'Стандарт',
    comfort_default: 'Премиум',
    sort_order: 5,
  },
  {
    id: 'l1',
    section_id: 'landscaping',
    name: 'Благоустройство участка',
    unit: 'м²',
    base_qty_formula: 'area * 2',
    variants: [
      { name: 'Минимум', material_price: 200, work_price: 300, delivery_price: 50 },
      { name: 'Стандарт', material_price: 400, work_price: 500, delivery_price: 100 },
      { name: 'Комплексное', material_price: 800, work_price: 1000, delivery_price: 200 },
    ],
    is_required: false,
    economy_default: 'Минимум',
    standard_default: 'Стандарт',
    comfort_default: 'Комплексное',
    sort_order: 1,
  },
];

export const DEFAULT_COMPANY_SETTINGS: CompanySettings = {
  company_name: 'ООО "СтройКальк"',
  logo_url: 'https://via.placeholder.com/150x50?text=StroiKalk',
  phone: '+7 (999) 123-45-67',
  email: 'info@stroikalk.ru',
  address: 'г. Москва, ул. Примерная, д. 1',
  requisites: 'ИНН: 7799999999, КПП: 779999999, БИК: 044525225',
  overhead_percent: 5,
  contingency_percent: 3,
  margin_percent: 15,
  usn_percent: 10,
};

export const DEFAULT_USERS = [
  {
    id: '1',
    email: 'admin@stroikalk.ru',
    password: 'admin123',
    name: 'Администратор',
    role: 'admin' as const,
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    email: 'manager@stroikalk.ru',
    password: 'manager123',
    name: 'Менеджер',
    role: 'manager' as const,
    created_at: new Date().toISOString(),
  },
];
